; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Breezedude]
platform = atmelsam
board = adafruit_itsybitsy_m0
framework = arduino
board_vid.0 = 0x03EB
board_build.usb_product = "Breezedude"
board_build.usb_manufacturer = "Breezedude"
board_build.variants_dir = variants
board_bootloader.file = "bootloader/bootloader-breezedude-16k.bin"
board_upload.offset_address = 0x4000
board_upload.maximum_size = 122112
extra_scripts = script.py
;upload_port = COM39
monitor_port = COM5
monitor_speed = 115200
lib_archive = no
build_flags = 
	-DUSE_TINYUSB -Iinclude/ -Os -flto -ffunction-sections -fdata-sections -Wl,--gc-sections -g3 
	-DLAST_BUILD_TIME=$UNIX_TIME 
	-DVERSION=\"1.1.0\"
	-DBREEZEDUDE_ENABLE_DISPLAY=0
	-DBREEZEDUDE_ENABLE_LORA_OTA=1
	-DBREEZEDUDE_RADIO_SX1276=0
	-DBREEZEDUDE_RADIO_SX1262=0
	-DBREEZEDUDE_RADIO_LLCC68=1
	-DBREEZEDUDE_ENABLE_GPS=0
	-DBREEZEDUDE_BARO_BMP280=0
	-DBREEZEDUDE_BARO_SPL06=0
	-DBREEZEDUDE_BARO_BMP3XX=0
	-DBREEZEDUDE_BARO_HP203B=1
	-DBREEZEDUDE_DEVELOP_MODE=0
lib_deps = 
	ricaun/ArduinoUniqueID@1.3.0
	paulstoffregen/Time@1.6.1
	kmackay/micro-ecc@1.0.0
	mikalhart/TinyGPSPlus@1.1.0
	jgromes/RadioLib@7.1.2
	adafruit/Adafruit BMP3XX Library@2.1.5
	;adafruit/Adafruit SSD1306@^2.5.13
    https://github.com/Granddyser/QMC5883P
upload_protocol = jlink
debug_tool = jlink
debug_server = 
	C:\Program Files\SEGGER\JLink_V838\JLinkGDBServerCL
	-singlerun
	-if
	SWD
	-select
	USB
	-port
	2331
	-device
	ATSAMD21G18A
